### ISSUE TITLE
Home - Página não encontrada (404)

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#1]
Ao acessar o endereço principal da aplicação, a página de entrada (home) não foi carregada.

![Issue - home](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/9b185f36-91af-46b7-9671-a9f4a58f03f7)

**Comment by Manuelaamorim** [comment]
Adicionamos

**Comment by Manuelaamorim** [comment]
Adicionamos a tela de login ao endereço principal da aplicação.

**Comment by Manuelaamorim** [comment]
O problema foi corrigido ao adicionar a página de login ao caminho do endereço principal da aplicação no arquivo urls.py.

![issue_login](https://github.com/Manuelaamorim/SmartSchool/assets/142773064/a5e45ce4-1b2b-4295-ab50-eab2fb7674fe)
