### ISSUE TITLE
Opção "Boletim" do menu sem funcionar

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#10]
Não há carregamento da página ao clicar na opção "Boletim" do navegador (menu).

![Screenshot 2024-04-06 214448](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/e6c7240c-bf20-405c-bef2-80106a93985e)

**Comment by lilymtbr** [comment]
Será implementado nas próximas entregas.

**Comment by luzianes** [comment]
Funcionalidade implementada:

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/26d08259-e60a-4632-bf6e-52182dfb4108)
