### ISSUE TITLE
Opção "Horários" do menu sem funcionar

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#11]
Não há carregamento da página ao clicar na opção "Boletim" do navegador (menu).

![Screenshot 2024-04-06 214448](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/9b7e8bbf-bd6c-487b-8496-089854ba5e27)

**Comment by lilymtbr** [comment]
Será implementado nas próximas entregas.

**Comment by MatheusVelame** [comment]
Problema resolvido após o código ser implementado para a entrega 3.
