### ISSUE TITLE
Opção "Perfil" do menu sem funcionar

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#12]
Não há carregamento da página ao clicar na opção "Perfil" do navegador (menu).

![Screenshot 2024-04-06 214448](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/1dc7bc22-6ec6-4241-99c3-5cc663875631)

**Comment by lilymtbr** [comment]
Será implementado nas próximas entregas.

**Comment by luzianes** [comment]
Funcionalidade temporariamente desativada.
