### ISSUE TITLE
Opção "SmartSchool" (home) gera uma página vazia

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#13]
Ao clicar na opção "SmartSchool" do menu, é carregada uma página vazia, sem qualquer informação.

![Screenshot 2024-04-06 214839](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/95fd1d28-638b-479f-ba9b-19c67748fd3d)

**Comment by lilymtbr** [comment]
Menu ainda está em fase de produção.

**Comment by luzianes** [comment]
A aplicação conta com uma página de entrada (Home) para cada usuário, como no exemplo abaixo (Home do funcionário):

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/8a72c3b1-91e8-4cf7-886e-109baa28b2e7)
