### ISSUE TITLE
Formatação da página "Dados de saúde" com problemas

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#14]
Para alguns usuários, a página "Dados de Saúde" não carrega de forma correta as configurações CSS/HTML.

![Screenshot 2024-04-06 215146](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/036f9225-ed09-4a2b-9037-258e7b6f8158)

**Comment by lilymtbr** [comment]
O problema foi concluído ajustando o css do projeto
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419881/de08321c-89ce-43cf-9658-448c9b50ab27)
