### ISSUE TITLE
Configurações CSS do menu Contato não estão funcionando 

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#18]
As configurações de estilo para a página de Contato não estão funcionando. O plano de fundo está branco e a cor da fonte em cinza claro, o que dificulta a visualização.

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/5bc3edd3-a4fe-4efb-9b7a-7f8d2554411b)

**Comment by luzianes** [comment]
Funcionalidade melhorada, mas ainda falta padronizar cores:

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/d5d06765-333b-48b8-82a5-7d26cadb32c5)

**Comment by MatheusVelame** [comment]
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419976/f507388d-9523-40e1-a588-61da2d5c6f6d)
problema resolvido após a padronização das cores realizadas no css.
