### ISSUE TITLE
Sublinhado nos links da tela login

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#21]
Necessidade de corrigir css da tela de login para eliminar os sublinhados dos links:

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/dcfd287c-652d-4689-b3cf-e3f578f9db0e)

**Comment by lilymtbr** [comment]
Resolvido! Correção no css.

![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419881/abc4e928-a950-4170-86dc-57005f2db668)
