### ISSUE TITLE
Visualização dos dados de saúde do aluno inadequada

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#25]
A visualização dos dados de saúde do aluno está pouco acessível em razão das cores utilizadas:

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/1e8e9e83-14f2-415d-a21b-e027825b3076)

**Comment by Manuelaamorim** [comment]
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142773064/9908d5a5-2044-4d8b-a933-9ab8c8df05a8)
O problema foi resolvido ao ajustar a cor da fonte no CSS
