### ISSUE TITLE
Visualização de frequência do aluno estruturada de forma inadequada

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#26]
A visualização da frequência do aluno foi construída de forma independente, sem conexão com as disciplinas cadastradas (existente no models.py).

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/7419c171-d65f-4467-be3e-f57af8659c35)

**Comment by MatheusVelame** [comment]
Problema resolvido após a implementação e conexão com disciplinas cadastradas.
