### ISSUE TITLE
Login do professor sem funcionar corretamente

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#28]
O login do professor não foi implementado e não está funcionando.

![Screenshot 2024-05-06 120748](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/3adf829c-c8ed-4ea8-8877-4902d3aceff3)

**Comment by MatheusVelame** [comment]
Problema resolvido após a criação da views do login do professor.
