### ISSUE TITLE
Erro de DoesNotExist caso o banco de dados esteja vazio

### ISSUE THREAD

**Issue by biapereira2** [Manuelaamorim/SmartSchool#36]
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419447/3a80a703-08f7-4d83-8684-183f9769ad07)
Acontece nas seguintes URLS: http://127.0.0.1:8000/notas/ , http://127.0.0.1:8000/horario/ e http://127.0.0.1:8000/frequencia/ quando o banco de dados está vazio, não acho que seja um problema, mas acho que é uma melhoria que pode ser feita, criar htmls para esses erros.

**Comment by MatheusVelame** [comment]
Problema não encontrado.
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419976/6dff1f34-1160-4393-a48a-3bf5457a402d)
Na aba de notas do aluno, caso o banco de dados esteja vazio, ele retorna uma mensagem de não cadastrados, o mesmo se aplica a horário e frequência.
