### ISSUE TITLE
Erro na aba de visualizar notas

### ISSUE THREAD

**Issue by biapereira2** [Manuelaamorim/SmartSchool#37]
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419447/451db4a2-1c3c-488f-b7c2-81e848f22f67)
Mesmo quando o aluno está cadastrado e as notas estão visíveis, é retornado o erro de aluno não encontrado.

**Comment by luzianes** [comment]
Corrigido.

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/7f499c44-30d1-4ae3-9ef3-f051c1f54a1c)
