### ISSUE TITLE
Falta de mensagem de erro nas páginas de visualizar horários e frequência

### ISSUE THREAD

**Issue by biapereira2** [Manuelaamorim/SmartSchool#38]
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419447/407e4eae-ac46-410f-ad34-ed65d12c4d59)
Quando o banco de dados está vazio, não é retornada nenhuma mensagem de erro, apenas uma página em branco. As mensagens de erro ficam disponíveis apenas no admin. 
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419447/32ae42a9-eaa8-43aa-ad9c-6568c855465a)

**Comment by MatheusVelame** [comment]
Problema resolvido após ajustar o html de horários e frequência, adicionando as mensagens de erro contida na views.
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419976/9886b095-7c80-490f-84f8-352d682a1775)
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419976/e7366411-9023-4c26-94c6-d8f37e2b1337)
