### ISSUE TITLE
Problema na página /admin

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#4]
A página /admin não carrega ao acessar o servidor:

![Issue - admin](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/65e17c3a-e8b6-45f3-82d2-b53642f6ce2b)

**Comment by MatheusVelame** [comment]
Problema resolvido após mudar a  "ROOT_URLCONF = 'appsmartschool.urls' " para "ROOT_URLCONF = 'smartschool.urls'", no arquivo settings.py.

![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419976/0642dd28-5544-4bc6-825c-5059d4d1c2af)
