### ISSUE TITLE
Cadastro de aluno não está salvando turma do aluno

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#41]
Ao cadastrar o aluno e informar todos os seus dados, a turma do aluno não está sendo gravada no banco de dados.

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/2e4901d3-4de9-4679-a17c-b012ba0da061)

**Comment by biapereira2** [comment]
Resolvido ajustando as views de cadastro de aluno 
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419447/4ee527d0-36e6-4d07-b5e7-16ee28274e17)
