### ISSUE TITLE
Cadastro de aluno não está salvando nome da escola

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#42]
Ao cadastrar um aluno e informar seus dados, o nome da escola não está sendo gravado no banco de dados.

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/e6cf6608-7fbd-45ca-a748-cfcb7e96fcc8)

**Comment by biapereira2** [comment]
Resolvido ajustando as views de cadastro de aluno 
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419447/2487f5ff-1540-4ec6-a669-cdda1eee3b5b)
