### ISSUE TITLE
Visualização de dados de saúde com CSS com falhas

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#43]
As configurações de estilo (CSS) da página de visualização dos dados de saúde estão com falhas, em desacordo com as demais views da aplicação. É preciso corrigir título e colocar moldura (quadro).

![WhatsApp Image 2024-05-31 at 09 01 47_1aad904a](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/ef3c482b-de9e-4dfc-bbb8-2cdff692921b)

**Comment by biapereira2** [comment]
Resolvido ajustando CSS dos dados de saúde
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419447/a0157df3-4bf2-4214-a01c-9b9acbc84692)
