### ISSUE TITLE
Em frequência, não está filtrando as disciplinas dos alunos

### ISSUE THREAD

**Issue by MatheusVelame** [Manuelaamorim/SmartSchool#67]
em https://fdssmartschool.azurewebsites.net/frequencia/, a aba de frequência dos alunos não estão sendo filtradas pela as matérias que a turma do aluno cadastrada contêm. (esta pegando todas as disciplinas cadastradas)
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419976/217aa90f-d3c9-4e2d-951d-8ff899018527)

**Comment by luzianes** [comment]
Corrigido.

![image](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/e3d76b4a-2e6d-4245-8e9a-4bab2f81d931)
