### ISSUE TITLE
Alerta para usuário não cadastrado

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#7]
Ao acessar informar os dados para login, o sistema não envia alerta para o caso de usuário não cadastrado, apenas recarrega a página com os campos em branco.

![Issue - msg de alerta (usuário não cadastrado)](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/752808f9-6fc3-415a-958e-2012772fce8e)

**Comment by Manuelaamorim** [comment]
O problema foi resolvido alterando o arquivo views.py para reconhecer CPF/senha inválidos e adicionando a mensagem no template HTML

![image](https://github.com/Manuelaamorim/SmartSchool/assets/142773064/09067ea3-a9df-4863-a8e5-33b0ebca3e51)
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142773064/5ba99655-a796-4ece-94e4-2819bf5e62db)
