### ISSUE TITLE
Correção da cor nos campos do formulário de contato

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#8]
Não é possível visualizar, com precisão, o que foi digitado nos campos do formulário de contato.

![Screenshot 2024-04-06 212633](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/45017f56-c7cf-42cb-9c39-44640556b1f8)

**Comment by MatheusVelame** [comment]
O problema foi resolvido, após realizar mudanças a parte do CSS do código.
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419976/60afd297-063d-42d6-bf9e-b1e28dd332dd)
![image](https://github.com/Manuelaamorim/SmartSchool/assets/142419976/8d98199a-085c-4c4c-bce1-6b9a703c78c5)
