### ISSUE TITLE
Problema no CSS da página de frequência

### ISSUE THREAD

**Issue by luzianes** [Manuelaamorim/SmartSchool#9]
As formatações constantes no arquivo CSS da página de frequência não estão funcionando adequadamente.

![Screenshot 2024-04-06 213715](https://github.com/Manuelaamorim/SmartSchool/assets/144596701/e96f379d-7b82-411b-999c-7ed82afd0caa)

**Comment by Manuelaamorim** [comment]
O problema foi concluído ajustando o css do projeto
